<?php

namespace CS\ApplicationsBundle\Repository;

/**
 * FichiersUpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichiersUpRepository extends \Doctrine\ORM\EntityRepository
{
}
