<?php

namespace CS\ApplicationsBundle\Repository;

/**
 * SecuriteCommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecuriteCommentaireRepository extends \Doctrine\ORM\EntityRepository
{
}
