<?php

namespace CS\ApplicationsBundle\Repository;

/**
 * TypeCommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCommentaireRepository extends \Doctrine\ORM\EntityRepository
{
}
