<?php

namespace CS\ServeursBundle\Repository;
use  Doctrine\ORM\Tools\Pagination\Paginator ;
/**
 * ServeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServeurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList($page=1, $maxperpage=20)
    {
        $q = $this->_em->createQueryBuilder()
            ->select('serveurs')
            ->from('CSServeursBundle:Serveur','serveurs')
        ;

        $q->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);

        return new Paginator($q);
    }
}
