<?php

namespace CS\ServeursBundle\Repository;

/**
 * TypeServeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeServeurRepository extends \Doctrine\ORM\EntityRepository
{
}
